---
# defaults file for bastion host

# Package configuration
rhel_repositories:
  - { name: 'rhel-x86_64-server-7', baseurl: '{{ repo_base_url }}/rhel-7-server-rpms', description: 'Red Hat Enterprise Linux 7' }
  - { name: 'rhel-x86_64-server-rh-common-7', baseurl: '{{ repo_base_url }}/rhel-7-server-rh-common-rpms', description: 'Red Hat Enterprise Linux 7 Common' }
  - { name: 'rhel-x86_64-server-extras-7', baseurl: "{{ repo_base_url }}/rhel-7-server-extras-rpms", description: 'Red Hat Enterprise Linux 7 Extras' }
  - { name: 'rhel-x86_64-server-optional-7', baseurl: "{{ repo_base_url }}/rhel-7-server-optional-rpms", description: 'Red Hat Enterprise Linux 7 Optional' }

bastion_enabled_repos: 'rhel-x86_64-server-7,rhel-x86_64-server-extras-7,rhel-x86_64-server-optional-7,rhel-x86_64-server-rh-common-7'
bastion_packages:
  - nfs-utils
  - vim
  - iptables-services
  - ntp

# Services

enabled_services:
  - ntpd
  - iptables
  - nfs-server

disabled_services:
  - firewalld
  - postfix
  - wpa_supplicant

# Networking

internal_network: 192.168.122.0/24

# NFS configuration

exports_url: https://raw.githubusercontent.com/RedHatDemos/RHCLS_ScalableInfrastructure/master/exports

nfs_export_dirs:
  - /exports/cinder/paris
  - /exports/cinder/tokyo
  - /exports/cinder/newyork

