---
# tasks file for bastion

- name: Include firewall (iptables) rules
  static: yes
  include: iptables.yml

- name: Include package management and installation task
  static: yes
  include: services.yml

- name: Configure /etc/exports
  get_url:
    url: "{{ exports_url }}"
    dest: /etc/exports
    mode: 0644
    force: yes
  notify: Export NFS
#
