---
# tasks file for bastion

- name: Include firewall (iptables) rules
  static: yes
  include: iptables.yml

- name: Include package management and installation task
  static: yes
  include: services.yml

- name: Create directories for NFS export
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items: "{{ nfs_export_dirs }}"

- name: Configure /etc/exports
  get_url:
    url: "{{ exports_url }}"
    dest: /etc/exports
    mode: 0644
    force: yes
  notify: Export NFS
...
