- name: Disable the default subscription-manager repositories
  command: subscription-manager config --rhsm.manage_repos=0

- include: osp.yml
  static: no
  when: setup_osp|bool 

- include: bastion.yml
  static: no
  when: setup_bastion 
