- name: Disable the default subscription-manager repositories
  command: subscription-manager config --rhsm.manage_repos=0

# All the variables have a default set. Those, however can be overriden any time (defaults have the lowest var priority). 

- include: osp.yml
  when: setup_osp

- include: bastion.yml
  when: setup_bastion 


