---
# tasks file for bastion
- name: Disable the default subscription-manager repositories
  command: subscription-manager config --rhsm.manage_repos=0 

- name: RHEL7 repository configuration
  yum_repository:
    name: "{{ item.name }}"
    baseurl: "{{ item.baseurl }}"
    description: "{{ item.description }}"
    gpgcheck: no
    file: rhel7
  with_items: "{{ rhel_repositories }}"

- name: Enable the required repositories ones only
  yum:
    name: "*"
    disablerepo: "*"
    enablerepo: "rhel-x86_64-server-7,rhel-x86_64-server-extras-7,rhel-x86_64-server-optional-7,rhel-x86_64-server-rh-common-7"

#- name: Debug
#  debug: 
#    msg: "{{ vars }}"

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ bastion_packages }}"

- name: Configure /etc/exports
  get_url:
    url: "{{ exports_url }}"
    dest: /etc/exports
    mode: 0644
    force: yes
  notify: Export NFS
#
