- name: Disable the default subscription-manager repositories
  command: subscription-manager config --rhsm.manage_repos=0

# All the variables have a default set. Those, however can be overriden any time (defaults have the lowest var priority). 

- name: RHEL7 repository configuration
  yum_repository:
    name: "{{ item.name }}"
    baseurl: "{{ item.baseurl }}"
    description: "{{ item.description }}"
    gpgcheck: no
    file: rhel7
  with_items: "{{ rhel_repositories }}"

- name: Enable the required repositories only
  yum:
    name: "*"
    disablerepo: "*"
    enablerepo: "{{ enabled_repositories }}"

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ bastion_packages }}"

