---
# This playbook configures the Bastion VM used for RHPDS in Ravello.
- name: Configuring Bastion VM used for RHPDS in Ravello.
  hosts: $servername
  tags:
    - pre-check
  remote_user: root

  tasks:
   - name: Include repository configuration
     include: repositories.yml

   - name: Disable all repos
     yum:
       disablerepo: '*'

   - name: Enable required repos
     yum: 
       enablerepo: "rhel-x86_64-server-7, rhel-x86_64-server-extras-7, rhel-x86_64-server-optional-7, rhel-x86_64-server-rh-common-7"

   - name: Install required packages
     yum:
       name: "{{ item }}"
       state: latest
     with_items:
     - nfs-utils

   - name: Configure /etc/exports
     get_url: 
       url: https://github.com/RedHatDemos/RHCLS_ScalableInfrastructure/blob/master/exports
       dest: /etc/exports 
       mode: 0644
       force: yes
       notify: Export NFS

  handlers:
    - name: Export NFS
      command: exportfs -ra

...
