---
# This playbook configures the Bastion VM used for RHPDS in Ravello.
remote_user: root
  tasks:
   - name: Capture, disable and enable repos
     get_url: http://www.opentlc.com/scripts/rhel7.repo dest=/etc/yum.repos.d/rhel7.repo mode=0644
     get_url: http://www.opentlc.com/scripts/redhat.repo dest=/etc/yum.repos.d/redhat.repo mode=0644
     yum: disablerepo=*
     yum: enablerepo=rhel-x86_64-server-7,rhel-x86_64-server-extras-7,rhel-x86_64-server-openstack-8,rhel-x86_64-server-rh-common-7
