--- 
  - name: RHEL7 repository configuration
    yum_repository:
      name: "{{ item.name }}"
      baseurl: "{{ item.baseurl }}"
      file: rhel7.repo
    with_items:
      - { name: 'Red Hat Enterprise Linux 7', baseurl: '***REMOVED***rhel-7-server-rpms' }
      - { name: 'Red Hat Enterprise Linux 7 Common', baseurl: '***REMOVED***rhel-7-server-rh-common-rpms' }
      - { name: 'Red Hat Enterprise Linux 7 Extras', baseurl: '***REMOVED***rhel-7-server-extras-rpms' }
      - { name: 'Red Hat Enterprise Linux 7 Optional', baseurl: '***REMOVED***rhel-7-server-optional-rpms' }

  - name: Disable all repos
    yum:
      disablerepo: '*'

  - name: Enable required repos
    yum:
      enablerepo: "rhel-x86_64-server-7, rhel-x86_64-server-extras-7, rhel-x86_64-server-optional-7, rhel-x86_64-server-rh-common-7"
