---
# This playbook configures the all-in-one RHEL OSP VMs used for RHCLS Scalable Infrastructure demo.
- hosts: $servername
  tags: 
    - pre-check
  remote_user: root
  tasks:
   - name: Capture RHEL7 repo config
     get_url: http://www.opentlc.com/scripts/rhel7.repo dest=/etc/yum.repos.d/rhel7.repo mode=0644
   - name: Capture redhat repo config
     get_url: http://www.opentlc.com/scripts/redhat.repo dest=/etc/yum.repos.d/redhat.repo mode=0644
   - name: Disable all repos
     yum: disablerepo=*
   - name: Enable required repos
     yum: enablerepo=rhel-x86_64-server-7,rhel-x86_64-server-extras-7,rhel-x86_64-server-openstack-8,rhel-x86_64-server-rh-common-7
   - name: Remove conflicting packages
     yum: state=absent name=NetworkManager
   - name: Install required packages
     yum: state=present name={{ item }}
     with items:
     - openstack-packstack
     - python-redis
     - kernel
     - mongodb
     - wget
   - name: Capture answers file for allinone OSP install
     get_url: <path to answers file> dest=/root
   - name: Install OSP using answers file
     local_action: command /usr/bin/packstack --answer-file=/root/answers.txt
   - name: Capture glance image for Ubuntu
     get_url: <location for Ubuntu image>
   - name: Capture glance image for Windows
     get_url: <loation for Windows image>
   - name: Capture glance image for RHEL
     get_url: <location for RHEL image>
   - name: Source keystone credentials
     local_action: source ./keystonerc_admin
   - name: Import Ubuntu cloud image into glance
     local_action: command /usr/bin/glance image-upload --name "Ubuntu" --file /root/<cloud_images>
   - name: Import Windows cloud image into glance
     local_action: command /usr/bin/glance image-upload --name "Windows" --file /root/<cloud_images>
   - name: Import RHEL cloud image into glance
     local_action: command /usr/bin/glance image-upload --name "RHEL" --file /root/<cloud_images>
   - name: Create Ubuntu instance from glance image
     local_action: command nova boot --image Ubuntu --flavor m1.small Ubuntu
   - name: Create Windows instance from glance image
     local_action: command nova boot --image Windows --flavor m1.medium Windows
   - name: Create RHEL instance from glance image
     local_action: command nova boot --image RHEL --flavor m1.small RHEL
