bastion_host: bastion 
remote_ssh_user: root
setup_bastion: true
setup_osp: false
# This below is just a workaround, it has to be configured someplace, but since OSP is in the works, this will do.
osp_repositories: none
repo_base_url: http://repo_fqdn_address/repos
